# Goal of the linter is to check the syntax, formatting, spacing, indentation etc.

name: Auto-linter

on:
  push:
    paths: "*.py"


jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/Clone the code
        uses: actions/checkout@v7
        
    
